# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#    campaignchain_location_google.example:
#        class: CampaignChain\Location\GoogleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
